// ===== 动作数据 =====
export const VIDEO_DATA = {
    "正手握拍": { bvid: "BV16E411w7B3", tip: "握拍就像握鸡蛋，太紧会受伤，太松会脱拍。" },
    "反手握拍": { bvid: "BV1aw411179M", tip: "拇指顶在宽面上是关键。" },
    "正手发高远球": { bvid: "BV1iW411p7pL", tip: "发球三步：侧身→抛球→挥拍。" },
    "反手发网前球": { bvid: "BV1pj411s7GR", tip: "力量控制是核心。" },
    "正手高远球": { bvid: "BV13C4y1t7Sn", tip: "击球点在右肩前上方最高处！" },
    "反手高远球": { bvid: "BV1dJBnBCEjs", tip: "先转身背对球网，拇指顶住宽面发力。" },
    "正手杀球": { bvid: "BV1wa4y1r7rj", tip: "杀球=高远球+手腕下压。" },
    "反手杀球": { bvid: "BV1Uu41117bb", tip: "转身要快，手腕爆发力下压。" },
    "正手吊球": { bvid: "BV1UA411Y74r", tip: "动作和高远球一模一样！击球瞬间收力。" },
    "反手吊球": { bvid: "BV1Rp4y1x7WW", tip: "转身准备，击球瞬间减力切削。" },
    "正手搓球": { bvid: "BV1KE421u7XS", tip: "拍面稍后仰，轻切球托底部。" },
    "反手搓球": { bvid: "BV1394y1o7Ya", tip: "拇指控制拍面角度，动作要轻柔。" },
    "正手推球": { bvid: "BV1Af4y1d7Pa", tip: "动作要小！手腕快速闪动发力。" },
    "反手推球": { bvid: "BV1v4G26pEnZ", tip: "拇指顶住发力，手腕闪动。" },
    "正手挑球": { bvid: "BV1RKCdYbEP4", tip: "降低重心！拍面后仰，向上挑球。" },
    "反手挑球": { bvid: "BV1Eg411u77k", tip: "反手握拍，降低重心，拇指顶住发力。" },
    "接杀球": { bvid: "BV1E56VYGEv8", tip: "降低重心，拍面前倾，借力打力。" },
    "并步": { bvid: "BV1mM411c7cS", tip: "两脚平行移动，小步快频。" },
    "交叉步": { bvid: "BV1cz41187yX", tip: "一脚迈出另一脚交叉迈过。" },
    "蹬跨步": { bvid: "BV14a4y1x7qE", tip: "降低重心→后脚蹬地→前脚大步跨出。" },
    "垫步": { bvid: "BV18Z421T7eB", tip: "击球前的小调整步，保持弹性。" },
    "起跳步法": { bvid: "BV1szHPzZEsD", tip: "降低重心→双脚蹬地起跳→空中引拍。" }
};

export const ACTIONS = [
    { id:1, name:"正手握拍", category:"基础", description:"虎口对准拍面窄边", difficulty:1, steps:["虎口对准拍框窄边","食指稍前于拇指","其余三指自然并拢","掌心空出","握拍松紧适度"], mistakes:["握拍太紧","虎口没有对准窄边"], tips:["像握鸡蛋","击球瞬间才握紧"], narration:"正手握拍是一切技术的基础。" },
    { id:2, name:"反手握拍", category:"基础", description:"拇指顶住宽面", difficulty:1, steps:["拇指顶住拍柄宽面","其余四指并拢","掌心空出","手腕放松","击球时拇指向前顶推"], mistakes:["拇指位置不对","握拍太紧"], tips:["拇指发力为主","手腕要灵活"], narration:"反手握拍的关键是拇指。" },
    { id:3, name:"正手发高远球", category:"基础", description:"左手抛球，右手正手击球", difficulty:2, steps:["侧身站位","左手持球","右手引拍","左手抛球","蹬地转体击球","随挥收拍"], mistakes:["击球点太低","没有侧身"], tips:["抛球要稳定","击球瞬间握紧"], narration:"发高远球是比赛的开始。" },
    { id:4, name:"反手发网前球", category:"基础", description:"反手轻击球托", difficulty:2, steps:["反手握拍","拍面稍后仰","轻推球托","控制拍面角度","落点在前场"], mistakes:["力量太大","拍面角度不对"], tips:["手腕发力为主","力量控制是核心"], narration:"反手发网前球靠的是手感。" },
    { id:5, name:"正手高远球", category:"基础", description:"正手将球击至对方后场", difficulty:2, steps:["侧身准备","引拍至身后","左手指向来球","蹬地转体","击球点在右肩前上方","手腕内旋发力","随挥收拍"], mistakes:["没有蹬地转体","击球点太低"], tips:["全身协调发力","击球点要高"], narration:"高远球是羽毛球最基本的技术。" },
    { id:6, name:"反手高远球", category:"基础", description:"用反手将球击至对方后场", difficulty:3, steps:["快速转身背对球网","引拍至左肩上方","拇指顶住宽面","蹬地转体","击球点在身体前上方","击球瞬间握紧","随挥恢复"], mistakes:["身体没转过去","击球点太低"], tips:["先转体再挥拍","击球点要在身体前方"], narration:"反手高远球难度较大。" },
    { id:7, name:"正手杀球", category:"进阶", description:"正手全力下压击球", difficulty:4, steps:["侧身准备","引拍至身后","蹬地转体身体前倾","击球点在右肩前上方","手腕用力下压","全速挥拍","快速回位"], mistakes:["击球点太低","没有下压手腕"], tips:["击球点要高","手腕要用力向下压"], narration:"杀球是羽毛球最具攻击性的技术。" },
    { id:8, name:"反手杀球", category:"进阶", description:"反手位全力下压击球", difficulty:5, steps:["快速转身背对球网","引拍至左肩上方","蹬地转体身体前倾","击球点在身体前上方","手腕爆发力下压","快速回位"], mistakes:["转身太慢","击球点不对"], tips:["转身要快","用拇指顶住发力"], narration:"反手杀球是最难的技术之一。" },
    { id:9, name:"正手吊球", category:"进阶", description:"正手轻吊，球贴网下落", difficulty:3, steps:["动作和高远球完全一致","引拍、转体、挥拍都一样","击球瞬间收力","拍面切削球托底部","控制球的弧度","球贴网而过"], mistakes:["动作太明显","力量控制不好"], tips:["动作要隐蔽","击球瞬间收力+切削"], narration:"吊球的精髓是动作隐蔽。" },
    { id:10, name:"反手吊球", category:"进阶", description:"反手位轻吊球", difficulty:4, steps:["转身准备背对球网","引拍像反手高远球","蹬地转体","击球瞬间减力","切削球托","球贴网而过"], mistakes:["动作太慢","力量控制不好"], tips:["转身要快","手腕要灵活"], narration:"反手吊球和反手高远球动作要一致。" },
    { id:11, name:"正手搓球", category:"进阶", description:"正手搓球，球旋转过网", difficulty:3, steps:["拍面稍后仰","轻切球托底部","手腕向前推送","控制拍面角度","球旋转过网","落点在前场"], mistakes:["力量太大","拍面角度不对"], tips:["手腕要柔和","切削要到位"], narration:"搓球靠的是手感。" },
    { id:12, name:"反手搓球", category:"进阶", description:"反手搓球", difficulty:3, steps:["反手握拍","拍面稍后仰","轻切球托","控制拍面角度","球旋转过网"], mistakes:["没有切削","力量控制不好"], tips:["拇指控制拍面角度","动作要轻柔"], narration:"反手搓球同样靠手感。" },
    { id:13, name:"正手推球", category:"进阶", description:"正手快速推球至后场两角", difficulty:3, steps:["拍面稍前倾","手腕快速闪动","击球点在身体前方","发力短促","球飞向后场","控制落点"], mistakes:["动作太大","击球点太晚"], tips:["动作要小","手腕要快"], narration:"推球靠的是手腕的爆发力。" },
    { id:14, name:"反手推球", category:"进阶", description:"反手快速推球", difficulty:3, steps:["反手握拍","拍面前倾","手腕闪动发力","击球点在身前","球飞向后场"], mistakes:["动作太大","没有用拇指发力"], tips:["拇指顶住发力","动作要干脆"], narration:"反手推球靠拇指发力。" },
    { id:15, name:"正手挑球", category:"基础", description:"正手将吊球挑至后场", difficulty:2, steps:["降低重心","移动到球的下方","拍面后仰","向上挑球","球飞向后场","控制落点"], mistakes:["没有降低重心","挑球太高或太低"], tips:["重心要低","手腕要放松"], narration:"挑球的关键是降低重心。" },
    { id:16, name:"反手挑球", category:"基础", description:"反手将吊球挑至后场", difficulty:2, steps:["降低重心","反手握拍","移动到球的下方","向上挑球","球飞向后场"], mistakes:["没有用拇指发力","落点不准"], tips:["拇指顶住发力","控制好力度"], narration:"反手挑球靠拇指发力。" },
    { id:17, name:"接杀球", category:"基础", description:"接对方杀球挡回", difficulty:3, steps:["降低重心","预判方向","拍面前倾","借力打力","控制回球落点","回球要低"], mistakes:["反应太慢","没有降低重心"], tips:["预判要准","借力打力"], narration:"接杀球靠的是预判和借力。" },
    { id:18, name:"并步", category:"步法", description:"两脚平行移动", difficulty:1, steps:["一脚先迈出","另一脚跟上保持平行","间距保持不变","重心平稳","小步快频"], mistakes:["两脚交叉","重心起伏太大"], tips:["小步快频","保持身体直立"], narration:"并步是最基本的步法。" },
    { id:19, name:"交叉步", category:"步法", description:"两脚交叉移动", difficulty:2, steps:["一脚迈出","另一脚交叉迈过","连续交叉","到位后蹬地","击球后回位"], mistakes:["步子太大","重心不稳"], tips:["步幅适中","身体要协调"], narration:"交叉步用于长距离移动。" },
    { id:20, name:"蹬跨步", category:"步法", description:"最后一步蹬地跨出", difficulty:2, steps:["降低重心","后脚蹬地","前脚大步跨出","脚跟先着地","身体前倾击球"], mistakes:["没有蹬地","跨步太小"], tips:["蹬地要有力","脚跟先着地"], narration:"蹬跨步用于接网前球。" },
    { id:21, name:"垫步", category:"步法", description:"击球前的小调整步", difficulty:1, steps:["小步调整位置","保持平衡","调整节奏","准备击球","迅速回位"], mistakes:["垫步太大","没有垫步"], tips:["小步快速","垫步要轻"], narration:"垫步是击球前的小调整。" },
    { id:22, name:"起跳步法", category:"步法", description:"跳起击球的步法", difficulty:3, steps:["降低重心","双脚蹬地起跳","空中引拍","最高点击球","落地弯曲缓冲","迅速回位"], mistakes:["起跳太低","没有蹬地"], tips:["蹬地要有力","空中保持平衡"], narration:"起跳步法用于杀球和吊球。" }
];
